### ISSUE TITLE
Data type issue

### ISSUE THREAD

**Issue by PoomSmart** [theos/headers#1]
I don't think brightness level is stored and set as CGFloat. It should be just float. This might be a culprit of BrightVol (https://github.com/hbang/BrightVol) issues with arm64.

You can check out my fork here: https://github.com/PoomSmart/BrightVol

**Comment by kirb** [comment]
Figured it may have been that… Have you tested this on a 64-bit device?

**Comment by PoomSmart** [comment]
I don't own any 64-bit devices. I can only try to help you figuring it out.

**Comment by kirb** [comment]
Got someone to test, doesn't seem to be it unfortunately. Makes me wonder how others have gotten around it because I haven't seen any sort of problem with this function mentioned elsewhere.

**Comment by kirb** [comment]
Is this fixed?

**Comment by PoomSmart** [comment]
Could be my mistake. I just wanted to clean up my activities on GitHub and this one might be by wrong assumption that this issue is already fixed.

**Comment by PoomSmart** [comment]
Can it be BKSDisplayBrightnessSet(float, int) instead of BKSDisplayBrightnessSet(float, NSInteger)?

**Comment by PoomSmart** [comment]
Outdated.
