### ISSUE TITLE
[Suggestion] Standardize .modulemap vendor location

### ISSUE THREAD

**Issue by L1ghtmann** [theos/headers#83]
What are the steps to reproduce this issue?
-------------------------------------------
N/A

What happens?
-------------
N/A

What were you expecting to happen?
----------------------------------
N/A

Any logs, error output, etc?
----------------------------

Any other comments?
-------------------
Note: I am not well versed on clang modules/module maps. 

Following the merge of the Orion [theos/lib pr](https://github.com/theos/lib/pull/15/files), half of the module maps provided by Theos will be located in the lib vendor directory while the other half, listed below, will be present in this repo. I believe the libraries corresponding to the various maps in this repo, save for Preferences, are vended by Theos, so it may be worth moving all module maps to the respective directories here or the respective directories in theos/lib for consistency. 
```
./libundirect/module.modulemap
./Preferences/module.modulemap
./libactivator/module.modulemap
./AppList/module.modulemap
./libhooker/module.modulemap
./Flipswitch/module.modulemap
./rocketbootstrap/module.modulemap
./libprefs/module.modulemap
```

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by leptos-null** [comment]
I think everything works-as-expected, however theos has two uses for `libs`, which may be confusing.

`libs` contains both libraries and frameworks:
- Frameworks self-contain their binary, headers and now modulemap. 
- Libraries in `libs` are just binaries (or their tbd equivalent) - their headers (and now modulemaps) live here in `headers`.

I'm not sure it makes sense to have another directory dedicated to frameworks and the pattern described here should allow theos to have a consistent location for modulemaps (depending on the type of distribution).

**Comment by L1ghtmann** [comment]
Right, I just wasn't sure if the module maps made more sense alongside the discrete libs or here. Re your comment in the other thread, seems like everything is in a good spot. Thanks again for the clarification!
